using System.Collections.Generic;
using UnityEngine;

namespace TBSplineS
{
    /// <summary>
    /// Tags an object as generated by TBSplineS so it can be cleaned up on the next rebuild. Do not add it by
    /// hand: any object carrying it is destroyed when the generator that owns it rebuilds.
    /// </summary>
    public sealed class TbsSpawnedMarker : MonoBehaviour
    {
    }

    /// <summary>
    /// How many objects an object controller places, and where.
    /// </summary>
    public enum TbsSpawnMethod
    {
        /// <summary>Places a fixed number of objects, spread evenly along the spline.</summary>
        Count,

        /// <summary>Places one object per knot, at the knots themselves.</summary>
        Points
    }

    /// <summary>
    /// Instantiates prefabs along the spline with optional randomized offset, rotation and scale. Spawning is
    /// deterministic for a given seed, so the same layout is reproduced on every rebuild.
    /// </summary>
    [ExecuteAlways]
    [AddComponentMenu("TBSplineS/Object Controller")]
    public sealed class TbsObjectController : TbsSplineUser
    {
        [SerializeField] GameObject[] _objects = new GameObject[0];
        [SerializeField] TbsSpawnMethod _spawnMethod = TbsSpawnMethod.Count;
        [SerializeField, Min(0)] int _spawnCount = 10;
        [SerializeField] TbsMeshIteration _iteration = TbsMeshIteration.Ordered;
        [SerializeField] int _seed = 12345;
        [SerializeField] Vector2 _minOffset;
        [SerializeField] Vector2 _maxOffset;
        [SerializeField] bool _applyRotation = true;
        [SerializeField] Vector3 _minRotation;
        [SerializeField] Vector3 _maxRotation;
        [SerializeField] bool _applyScale;
        [SerializeField] float _minScale = 1f;
        [SerializeField] float _maxScale = 1f;

        readonly List<GameObject> _spawned = new List<GameObject>();

        /// <summary>Prefabs to place. They are cycled in order, or picked at random depending on the iteration mode.</summary>
        public GameObject[] Objects
        {
            get => _objects;
            set { _objects = value ?? new GameObject[0]; SetDirty(); }
        }

        /// <summary>How many objects to place when <see cref="SpawnMethod"/> is <see cref="TbsSpawnMethod.Count"/>.</summary>
        public int SpawnCount
        {
            get => _spawnCount;
            set { _spawnCount = Mathf.Max(0, value); SetDirty(); }
        }

        /// <summary>Whether objects are spread evenly or placed one per knot.</summary>
        public TbsSpawnMethod SpawnMethod
        {
            get => _spawnMethod;
            set { _spawnMethod = value; SetDirty(); }
        }

        /// <summary>Number of objects placed by the most recent build.</summary>
        public int SpawnedCount => _spawned.Count;

        protected override void PostBuild()
        {
            ClearSpawned();
            if (_objects == null || _objects.Length == 0) return;
            TbsSplineCache cache = ResolveCache();
            if (cache == null) return;

            int count = _spawnMethod == TbsSpawnMethod.Points ? cache.Spline.Count : _spawnCount;
            if (count <= 0) return;

            var random = new System.Random(_seed);
            int splineIndex = ResolvedSplineIndex;
            TbsSample sample = default;
            for (int i = 0; i < count; i++)
            {
                float localT;
                if (_spawnMethod == TbsSpawnMethod.Points && _computer != null)
                    localT = ClipPercent(_computer.GetKnotPercent(splineIndex, i));
                else
                    localT = count > 1 ? (float)i / (count - 1) : 0f;

                Evaluate(localT, ref sample);
                GameObject prefab = PickObject(i, random);
                if (prefab == null) continue;

                GameObject instance = Instantiate(prefab, transform);
                instance.name = prefab.name;
                instance.AddComponent<TbsSpawnedMarker>();

                Vector3 right = sample.Right;
                Vector3 up = sample.Up;
                float ox = Mathf.Lerp(_minOffset.x, _maxOffset.x, (float)random.NextDouble());
                float oy = Mathf.Lerp(_minOffset.y, _maxOffset.y, (float)random.NextDouble());
                instance.transform.position = sample.Position + right * ox + up * oy;

                if (_applyRotation)
                {
                    Vector3 euler = new Vector3(
                        Mathf.Lerp(_minRotation.x, _maxRotation.x, (float)random.NextDouble()),
                        Mathf.Lerp(_minRotation.y, _maxRotation.y, (float)random.NextDouble()),
                        Mathf.Lerp(_minRotation.z, _maxRotation.z, (float)random.NextDouble()));
                    instance.transform.rotation = sample.Rotation * Quaternion.Euler(euler);
                }
                else
                {
                    instance.transform.rotation = prefab.transform.rotation;
                }

                Vector3 scale = prefab.transform.localScale;
                if (_applyScale) scale *= Mathf.Lerp(_minScale, _maxScale, (float)random.NextDouble());
                instance.transform.localScale = scale;

                _spawned.Add(instance);
            }
        }

        GameObject PickObject(int index, System.Random random)
        {
            if (_objects.Length == 0) return null;
            int i = _iteration == TbsMeshIteration.Random ? random.Next(_objects.Length) : index % _objects.Length;
            return _objects[i];
        }

        void ClearSpawned()
        {
            for (int i = 0; i < _spawned.Count; i++) DestroyObject(_spawned[i]);
            _spawned.Clear();
            var markers = GetComponentsInChildren<TbsSpawnedMarker>(true);
            for (int i = 0; i < markers.Length; i++)
                if (markers[i] != null) DestroyObject(markers[i].gameObject);
        }

        static void DestroyObject(GameObject go)
        {
            if (go == null) return;
            if (Application.isPlaying) Destroy(go);
            else DestroyImmediate(go);
        }
    }
}
